[package]
name = "pomodoro-iced"
version = "0.1.0"
edition = "2024"

[lib]
name = "pomodoro_iced"
crate-type = ["cdylib", "rlib"]

[dependencies]
iced = { version = "0.14", features = ["tokio"] }

android-activity = { version = "0.6", features = ["native-activity"] }

[package.metadata.android]
package = "com.jyotiraditya.pomodoro"
build_targets = ["aarch64-linux-android"]

[package.metadata.android.sdk]
target_sdk_version = 35
min_sdk_version = 23
